### ISSUE TITLE
JavaScript Error on mouse leave: "getExerciseResult is not a function"

### ISSUE THREAD

**Issue by BiLachner** [mebis-lp/moodle-qtype_geogebra#45] opened 2022-04-17 05:51 UTC
![2022-04-17_07-42](https://user-images.githubusercontent.com/13196996/163702438-2a711f91-ff56-422f-aece-815d5bbaa9be.png)

Hi, here is an error, we get while using a GeoGebra file. You can find ist here: https://www.geogebra.org/m/mpcwwb2q

And I can't finish the test, even if my result was right.

The problem (i.e. the error message) does not only occur with us in Rhineland-Palatinate, but also with a colleague in Switzerland who has his own moodle instance for testing.

Can you see if it is due to my drawing? Or is something missing? Could it be that the plugin is too old?
Since I'm not an administrator, I can't change anything in the short term, but I would pass it on.

Regards, Birgit

**Comment by PhMemmel** [comment] 2022-04-17 10:18
Thanks @BiLachner for reporting this. Could you please provide the settings you made for this question type by, for example, pasting some screenshots of the settings? Could you also please elaborate how exactly moodle is supposed to get/extract/calculate the result from the GeoGebra applet you provided?

I stumbled over this error before, it happens on all current assignments. Still trying to figure out what this function call is supposed to do :-)
But I can confirm that this error in general does not prevent moodle from reading the boolean variables of the geogebra applet to check if the solution is correct or not, so maybe we have two different issues here.

**Comment by PhMemmel** [comment] 2022-04-22 08:36
Hi @BiLachner,
I sent a PR to solve this issue. It definitely removes the error. I hope that this also solves the problem of the question not being graded correctly. Please let us know if this part of the problem is solved. If not, please open a new issue for that problem and please provide an example ggb file with the exact settings you did.

**Comment by BiLachner** [comment] 2022-04-22 14:00
As far as I understand the informationswith the pull request, you changes haven't been added yet. When it is done, I'll contact our admin to update and have a look.
Thanks!

**Comment by PhMemmel** [comment] 2022-04-22 14:05
Yes, if you don't manage a test system where you can manually checkout the changes, you would have to wait until this has been reviewed and merged and a new release has been published on moodle.org.

**Closed** 2022-04-28 13:13 UTC

**Comment by PhMemmel** [comment] 2022-05-04 07:03
@BiLachner A new version just has been released. You can update the plugin in your moodle and see if the bug is fully gone. It would be awesome if you could let me know, if especially the problem with not being able to finish the task could be solved with this fix. Thanks in advance.
